  on:
    push:
      branches: 
      - "main"

  concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

  jobs:
    ld-code-refs:
      name: LaunchDarkly Code References
      runs-on: ubuntu-latest
      steps:
      - 
        uses: actions/checkout@v3
        with:
          fetch-depth: 11 
      - 
        name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v2.9.1
        with:
          accessToken: ${{ secrets.LD_ACCESS_TOKEN }}